version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: editorial
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  app:
    build: ./proynodjs
    container_name: node_app
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
