version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=editorial
    ports:
      - 3307:3306
    volumes:
      - db:/dockerVolumes/var/lib-mysql

  app:
    depends_on:
      - mysqldb
    build: ./proynodjs
    restart: unless-stopped
    ports:
      - 4000:4000
    stdin_open: true
    tty: true

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
